### ISSUE TITLE
Make the URL change

### ISSUE THREAD

**Issue by fosils** [OO-developers/WebsiteDK#38]
I am trying in insert facebook conversion points to the website. I can only do this by each conversion point having its own unique url like ebogholderen.dk/sign-up or ebogholderen.dk/contact-us

Please make it so that these buttons will lead the user to such a url since they indicate that the visitor is very interested:
http://screencast.com/t/0MhcIXOz 
http://screencast.com/t/gYuZpb6fttK0
and also all similar buttons which will result in a sign up or contact. 

I am not sure whether you can implement this by using the javascript functions to set the url, so please research that. This is where I would use it in Facebook: http://screencast.com/t/AfnhDQpeG

@zazoley Are you up for this task? Please also resend your email, so I can communicate via email. Mine is mrdavidandersen@gmail.com

**Comment by zazoley** [comment]
Usually it can be done using special javascript events. I've done it for google analytics.
I think facebook should have something similar. I'll try to research it now.
My email: web.dandelion@gmail.com

**Comment by zazoley** [comment]
I think we can add Lead event by adding onclick event fbq('track', 'Lead'); for your buttons
![screen shot 2016-03-19 at 00 28 38](https://cloud.githubusercontent.com/assets/10416754/13889694/b4a57b78-ed69-11e5-832f-d67df87134a2.png)

**Comment by zazoley** [comment]
I did it for you. Except the online consultant button (I can't bind the event with this widget).

**Comment by fosils** [comment]
@zazoley I am sorry, I did not get notified about this post. Let's do it via emails instead.
